package HtmlLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HeadTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("<head>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<title>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$yctf));
    tgs.append("</title>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("<head>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<body>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty title$yctf = MetaAdapterFactory.getProperty(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a0646889c1L, 0x6e9a86a06468924aL, "title");
  }
}
