package HtmlLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HtmlDocument_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<!DOCTYPE html>");
    tgs.newLine();
    tgs.append("<html>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.content$cgUA)) {
      tgs.appendNode(item);
    }
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</body>");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("</html>");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink content$cgUA = MetaAdapterFactory.getContainmentLink(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064685dcfL, 0x6e9a86a0646862b2L, "content");
  }
}
