package HtmlLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HyperlinkTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<a href=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.href$TRa$));
    tgs.append("\">");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$h_8s));
    tgs.append("</a>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty href$TRa$ = MetaAdapterFactory.getProperty(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468c276L, 0x6e9a86a06468c7dbL, "href");
    /*package*/ static final SProperty text$h_8s = MetaAdapterFactory.getProperty(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468c276L, 0x6e9a86a06468c949L, "text");
  }
}
