package HtmlLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ImageTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<img src=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.file$bMcp));
    tgs.append("\" alt=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$jxfn));
    tgs.append("\">");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty file$bMcp = MetaAdapterFactory.getProperty(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468a4f8L, 0x6e9a86a06468aff3L, "file");
    /*package*/ static final SProperty text$jxfn = MetaAdapterFactory.getProperty(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468a4f8L, 0x6e9a86a06468b0f9L, "text");
  }
}
