package HtmlLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import HtmlLanguage.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import java.nio.charset.Charset;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.HeadTag:
        return new HeadTag_TextGen();
      case LanguageConceptSwitch.HtmlDocument:
        return new HtmlDocument_TextGen();
      case LanguageConceptSwitch.HyperlinkTag:
        return new HyperlinkTag_TextGen();
      case LanguageConceptSwitch.ImageTag:
        return new ImageTag_TextGen();
      case LanguageConceptSwitch.ParagraphTag:
        return new ParagraphTag_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.HtmlDocument$GU)) {
        String fname = getFileName_HtmlDocument(root);
        String ext = getFileExtension_HtmlDocument(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), Charset.forName(getEncoding_HtmlDocument()), root);
        continue;
      }
    }
  }
  private static String getFileName_HtmlDocument(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_HtmlDocument(SNode node) {
    return "html";
  }
  private static String getEncoding_HtmlDocument() {
    return "UTF-8";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept HtmlDocument$GU = MetaAdapterFactory.getConcept(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064685dcfL, "HtmlLanguage.structure.HtmlDocument");
  }
}
