package HtmlLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDivTag = createDescriptorForDivTag();
  /*package*/ final ConceptDescriptor myConceptHeadTag = createDescriptorForHeadTag();
  /*package*/ final ConceptDescriptor myConceptHtmlDocument = createDescriptorForHtmlDocument();
  /*package*/ final ConceptDescriptor myConceptHyperlinkTag = createDescriptorForHyperlinkTag();
  /*package*/ final ConceptDescriptor myConceptImageTag = createDescriptorForImageTag();
  /*package*/ final ConceptDescriptor myConceptParagraphTag = createDescriptorForParagraphTag();
  /*package*/ final ConceptDescriptor myConceptSimpleTag = createDescriptorForSimpleTag();
  /*package*/ final ConceptDescriptor myConceptUListItem = createDescriptorForUListItem();
  /*package*/ final ConceptDescriptor myConceptUnorderedListTag = createDescriptorForUnorderedListTag();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDivTag, myConceptHeadTag, myConceptHtmlDocument, myConceptHyperlinkTag, myConceptImageTag, myConceptParagraphTag, myConceptSimpleTag, myConceptUListItem, myConceptUnorderedListTag);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DivTag:
        return myConceptDivTag;
      case LanguageConceptSwitch.HeadTag:
        return myConceptHeadTag;
      case LanguageConceptSwitch.HtmlDocument:
        return myConceptHtmlDocument;
      case LanguageConceptSwitch.HyperlinkTag:
        return myConceptHyperlinkTag;
      case LanguageConceptSwitch.ImageTag:
        return myConceptImageTag;
      case LanguageConceptSwitch.ParagraphTag:
        return myConceptParagraphTag;
      case LanguageConceptSwitch.SimpleTag:
        return myConceptSimpleTag;
      case LanguageConceptSwitch.UListItem:
        return myConceptUListItem;
      case LanguageConceptSwitch.UnorderedListTag:
        return myConceptUnorderedListTag;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDivTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "DivTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x28eda459855c5c21L);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/2949194035394010145");
    b.version(3);
    b.aggregate("content", 0x28eda459855d1734L).target(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL).optional(true).ordered(true).multiple(true).origin("2949194035394058036").done();
    b.alias("Div");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHeadTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "HeadTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a0646889c1L);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022975937");
    b.version(3);
    b.property("title", 0x6e9a86a06468924aL).type(PrimitiveTypeId.STRING).origin("7969830514022978122").done();
    b.alias("Head");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "HtmlDocument", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064685dcfL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022964687");
    b.version(3);
    b.aggregate("content", 0x6e9a86a0646862b2L).target(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL).optional(true).ordered(true).multiple(true).origin("7969830514022965938").done();
    b.alias("html");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHyperlinkTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "HyperlinkTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468c276L);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022990454");
    b.version(3);
    b.property("href", 0x6e9a86a06468c7dbL).type(PrimitiveTypeId.STRING).origin("7969830514022991835").done();
    b.property("text", 0x6e9a86a06468c949L).type(PrimitiveTypeId.STRING).origin("7969830514022992201").done();
    b.alias("Hyperlink");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForImageTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "ImageTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a06468a4f8L);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022982904");
    b.version(3);
    b.property("file", 0x6e9a86a06468aff3L).type(PrimitiveTypeId.STRING).origin("7969830514022985715").done();
    b.property("text", 0x6e9a86a06468b0f9L).type(PrimitiveTypeId.STRING).origin("7969830514022985977").done();
    b.alias("Image");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParagraphTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "ParagraphTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064689886L);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022979718");
    b.version(3);
    b.property("text", 0x6e9a86a064689fa3L).type(PrimitiveTypeId.STRING).origin("7969830514022981539").done();
    b.alias("Paragraph");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSimpleTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "SimpleTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.class_(false, true, false);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/7969830514022967916");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUListItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "UListItem", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x28eda459855b7d16L);
    b.class_(false, false, false);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/2949194035393953046");
    b.version(3);
    b.property("text", 0x28eda459855babb9L).type(PrimitiveTypeId.STRING).origin("2949194035393964985").done();
    b.alias("Item ");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUnorderedListTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HtmlLanguage", "UnorderedListTag", 0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x28eda459855b64cbL);
    b.class_(false, false, false);
    // extends: HtmlLanguage.structure.SimpleTag
    b.super_(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x6e9a86a064686a6cL);
    b.origin("r:bd69ae55-c415-49bf-b242-3bef64367402(HtmlLanguage.structure)/2949194035393946827");
    b.version(3);
    b.aggregate("tags", 0x28eda459855b7b8eL).target(0x764a74ce76f54685L, 0xb653bb0758aa91c6L, 0x28eda459855b7d16L).optional(true).ordered(true).multiple(true).origin("2949194035393952654").done();
    b.alias("UList");
    return b.create();
  }
}
